### ISSUE TITLE
Some kernel functions do not vectorize using Intel CPUs and OpenCL 1.2

### ISSUE THREAD

**Issue by jjaguayo** [nengo/nengo-ocl#73]
When running the Nengo script 1-communication.py from @tcstewar 's repository nengo_benchmarks with the nengo_ocl backend, the following nengo_ocl kernel functions do not vectorize, 
- probes
- gemv_many_dots
- elementwise_inc
- cl_lif_2
- filter_synapse

The spec for the machine being run on as well as the environment are as follows:
- 64 64-bit Intel Xeon CPUs
- CentOS 6.6
- PyOpenCL 2015.1
- OpenCL 1.2 driver
- Python 2.7
- Nengo 2.0

After setting PYOPENCL_COMPILER_OUTPUT, I collected output from the terminal and will email it to @hunse .

**Comment by hunse** [comment]
I use the [AMD APP](http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/) now instead of the Intel one, and I no longer get messages like these. Also, I think all of the kernels have been revised in some way, so this probably has to be reinvestigated at the very least.

**Comment by drasmuss** [comment]
Closing this, as it is specific to CPU builds (whereas the primary use case for Nengo OCL is for GPUs), and there is at least a workaround as Eric suggested. But let us know if this is still impacting you and we can reopen!
